[package]
name = "knope"
description = "A command line tool for automating common development tasks"
version = "0.6.3"
authors = ["Dylan Anthony <contact@dylananthony.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/knope-dev/knope"
homepage = "https://knope-dev.github.io/knope/"
documentation = "https://knope-dev.github.io/knope/"
keywords = ["jira", "git", "github", "workflow", "script"]
categories = ["command-line-utilities", "development-tools"]
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
base64 = "0.20.0"
console = "0.15.5"
dialoguer = "0.10.3"
toml = "0.5.10"
serde_json = { version = "1.0.91", features = ["preserve_order"] }
git2 = { version = "0.15.0", default-features = false }
semver = "1.0.16"
execute = "0.2.11"
platform-dirs = "0.3.0"
git-conventional = "0.12.1"
ureq = { version = "2.6.1", features = ["json"] }
http = "0.2.8"
clap = { version = "4.0.32", features = ["cargo", "derive", "env"] }
itertools = "0.10.5"
miette = { version = "5.5.0", features = ["fancy"] }
thiserror = "1.0.38"
velcro = "0.5.4"
git-repository = "0.31.0"
log = "0.4.17"
env_logger = "0.10.0"

[dev-dependencies]
rstest = "0.16.0"
snapbox = "0.4.4"
tempfile = "3.3.0"
