[package]
name = "knope"
description = "A command line tool for automating common development tasks"
version = "0.2.0"
authors = ["Dylan Anthony <contact@dylananthony.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/knope-dev/knope"
homepage = "https://knope-dev.github.io/knope/"
documentation = "https://knope-dev.github.io/knope/"
keywords = ["jira", "git", "github", "workflow", "script"]
categories = ["command-line-utilities", "development-tools"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
base64 = "0.13.0"
console = "0.15.0"
dialoguer = "0.10.0"
toml = "0.5.8"
serde_json = { version = "1.0.80", features = ["preserve_order"] }
git2 = "0.14.3"
semver = "1.0.7"
execute = "0.2.10"
platform-dirs = "0.3.0"
git-conventional = "0.11.3"
ureq = { version = "2.4.0", features = ["json"] }
http = "0.2.7"
clap = { version = "3.1.6", features = ["cargo", "derive"] }
itertools = "0.10.3"
miette = { version = "4.2.1", features = ["fancy"] }
thiserror = "1.0.31"
velcro = "0.5.3"

[dev-dependencies]
snapbox = "0.2.9"
tempfile = "3.3.0"

[features]
