[package]
name = "knope"
description = "A command line tool for automating common development tasks"
version = "0.3.0"
authors = ["Dylan Anthony <contact@dylananthony.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/knope-dev/knope"
homepage = "https://knope-dev.github.io/knope/"
documentation = "https://knope-dev.github.io/knope/"
keywords = ["jira", "git", "github", "workflow", "script"]
categories = ["command-line-utilities", "development-tools"]
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.140", features = ["derive"] }
base64 = "0.13.0"
console = "0.15.1"
dialoguer = "0.10.2"
toml = "0.5.9"
serde_json = { version = "1.0.82", features = ["preserve_order"] }
git2 = "0.15.0"
semver = "1.0.12"
execute = "0.2.11"
platform-dirs = "0.3.0"
git-conventional = "0.12.0"
ureq = { version = "2.5.0", features = ["json"] }
http = "0.2.8"
clap = { version = "3.2.16", features = ["cargo", "derive"] }
itertools = "0.10.3"
miette = { version = "5.1.1", features = ["fancy"] }
thiserror = "1.0.31"
velcro = "0.5.3"

[dev-dependencies]
rstest = "0.15.0"
snapbox = "0.2.10"
tempfile = "3.3.0"

[features]
