[package]
name = "flow"
version = "0.1.0-rc.0"
authors = ["Dylan Anthony <contact@dylananthony.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
serde = { version = "1.0.118", features = ["derive"] }
base64 = "0.13.0"
color-eyre = "0.5.10"
ureq = { version = "1.5.4", features = ["json"] }
console = "0.13.0"
dialoguer = "0.7.1"
toml = "0.5.7"
serde_json = "1.0.60"
git2 = "0.13.12"
regex = "1.4.2"
semver = "0.11.0"
toml_edit = "0.2.0"
execute = "0.2.8"
