[package]
name = "knope"
description = "A command line tool for automating common development tasks"
version = "0.9.0"
authors = ["Dylan Anthony <contact@dylananthony.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/knope-dev/knope"
homepage = "https://knope-dev.github.io/knope/"
documentation = "https://knope-dev.github.io/knope/"
keywords = ["jira", "git", "github", "workflow", "script"]
categories = ["command-line-utilities", "development-tools"]
rust-version = "1.67"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.183", features = ["derive"] }
base64 = "0.21.2"
toml = "0.7.6"
serde_json = { version = "1.0.105", features = ["preserve_order"] }
git2 = { version = "0.17.2", default-features = false }
execute = "0.2.12"
platform-dirs = "0.3.0"
git-conventional = "0.12.4"
ureq = { version = "2.7.1", features = ["json"] }
http = "0.2.9"
clap = { version = "4.3.21", features = ["cargo", "string", "env"] }
itertools = "0.11.0"
miette = { version = "5.10.0", features = ["fancy"] }
thiserror = "1.0.47"
gix = "0.51.0"
log = "0.4.20"
env_logger = "0.10.0"
indexmap = { version = "2.0.0", features = ["serde"] }
inquire = { version = "0.6.2", default-features = false, features = [
  "crossterm",
] }
changesets = "0.2.1"
time = { version = "0.3.25" }

[dev-dependencies]
pretty_assertions = "1.4.0"
rstest = { version = "0.18.2", default-features = false }
snapbox = "0.4.10"
tempfile = "3.7.1"
