[package]
name = "dobby"
description = "A command line tool for automating common development tasks"
version = "0.1.0-rc.0"
authors = ["Dylan Anthony <danthony@triaxtec.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/triaxtec/dobby"
keywords = ["jira", "git", "github", "workflow", "script"]
categories = ["command-line-utilities", "development-tools"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.118", features = ["derive"] }
base64 = "0.13.0"
color-eyre = "0.5.10"
console = "0.13.0"
dialoguer = "0.7.1"
toml = "0.5.7"
serde_json = "1.0.60"
git2 = "0.13.13"
regex = "1.4.2"
semver = "0.11.0"
toml_edit = "0.2.0"
execute = "0.2.8"
platform-dirs = "0.3.0"
tokio = { version = "0.2.24", features = ["macros"]}
reqwest = { version = "0.10.10", features = ["json", "rustls"] }
octocrab = "0.8.1"

[dev-dependencies]
tempfile = "3.1.0"
