[workspace]
resolver = "2"
default-members = ["crates/knope"]
members = ["crates/knope", "crates/knope-versioning"]

[profile.release]
strip = true

[workspace.lints.rust]
unsafe_code = "forbid"
warnings = "deny"

[workspace.lints.clippy]
all = "deny"
pedantic = "deny"

# cargo-deny handles this
multiple_crate_versions = "allow"

# Don't panic!
panic = "deny"
exit = "deny"
unimplemented = "deny"
todo = "deny"
expect_used = "deny"
unwrap_used = "deny"
indexing_slicing = "deny"
missing_panics_doc = "forbid"
