[package]
name = "knope"
description = "A command line tool for automating common development tasks"
version = "0.14.0"
authors = ["Dylan Anthony <contact@dylananthony.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/knope-dev/knope"
homepage = "https://knope.tech"
documentation = "https://knope.tech"
keywords = ["semantic-version", "changelog", "changeset", "git", "github"]
categories = ["command-line-utilities", "development-tools"]
rust-version = "1.71.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.196", features = ["derive"] }
base64 = "0.21.7"
toml = "0.8.10"
serde_json = { version = "1.0.113", features = ["preserve_order"] }
git2 = { version = "0.18.2", default-features = false }
execute = "0.2.13"
platform-dirs = "0.3.0"
git-conventional = "0.12.4"
ureq = { version = "2.9.5", features = ["json"] }
http = "1.0.0"
clap = { version = "4.5.0", features = ["cargo", "string", "env"] }
itertools = "0.12.1"
miette = { version = "7.0.0", features = ["fancy"] }
thiserror = "1.0.57"
gix = { version = "0.58.0", default-features = false, features = [
  "max-performance-safe",
] }
log = "0.4.20"
env_logger = "0.11.2"
indexmap = { version = "2.2.3", features = ["serde"] }
inquire = { version = "0.6.2", default-features = false, features = [
  "crossterm",
] }
changesets = "0.2.2"
time = { version = "0.3.34" }
datta = "0.1.0"
serde_yaml = "0.9.31"
enum-iterator = "1.5.0"

[dev-dependencies]
pretty_assertions = "1.4.0"
rstest = { version = "0.18.2", default-features = false }
snapbox = "0.4.17"
tempfile = "3.10.0"

[profile.release]
strip = true
