[package]
name = "knope"
description = "A command line tool for automating common development tasks"
version = "0.13.4"
authors = ["Dylan Anthony <contact@dylananthony.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/knope-dev/knope"
homepage = "https://knope.tech"
documentation = "https://knope.tech"
keywords = ["semantic-version", "changelog", "changeset", "git", "github"]
categories = ["command-line-utilities", "development-tools"]
rust-version = "1.71.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.7"
changesets = "0.2.2"
clap = { version = "4.4.18", features = ["cargo", "string", "env"] }
datta = "0.1.0"
env_logger = "0.11.0"
execute = "0.2.13"
git-conventional = "0.12.4"
git2 = { version = "0.18.1", default-features = false }
gix = { version = "0.57.1", default-features = false, features = ["max-performance-safe", ] }
http = "1.0.0"
indexmap = { version = "2.1.0", features = ["serde"] }
inquire = { version = "0.6.2", default-features = false, features = ["crossterm", ] }
itertools = "0.12.0"
log = "0.4.20"
miette = { version = "5.10.0", features = ["fancy"] }
platform-dirs = "0.3.0"
reqwest = { version = "0.11.23", default-features = false, features = ["rustls-tls", "json"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = { version = "1.0.111", features = ["preserve_order"] }
serde_yaml = "0.9.30"
thiserror = "1.0.56"
time = { version = "0.3.31" }
tokio = { version = "1.35.1", default-features = false, features = ["macros", "rt-multi-thread"] }
toml = "0.8.8"

[dev-dependencies]
pretty_assertions = "1.4.0"
rstest = { version = "0.18.2", default-features = false }
snapbox = "0.4.16"
tempfile = "3.9.0"

[profile.release]
strip = true