[[workflows]]
name = "Start New Task"

    [[workflows.steps]]
    type = "SelectGitHubIssue"

    [[workflows.steps]]
    type = "SwitchBranches"

[[workflows]]
name = "Finish Development"

    [[workflows.steps]]
    type = "Command"
    command = "gh pr create --web -p WIP"

[[workflows]]
name = "Release"

    [[workflows.steps]]
    type = "Command"
    command = "git checkout main && git pull"

    [[workflows.steps]]
    type = "BumpVersion"
    rule = "Pre"
    value = "rc"

    [[workflows.steps]]
    type = "Command"
    command = "git add Cargo.toml"

    [[workflows.steps]]
    type = "Command"
    command = "git commit -m \"bump to version\""
    variables = {"version" = "Version"}

    [[workflows.steps]]
    type = "Command"
    command = "git push && git fetch -p -P"

    [[workflows.steps]]
    type = "Command"
    command = "gh release create --title version v.version --draft"
    variables = {"version" = "Version"}

    [[workflows.steps]]
    type = "Command"
    command = "gh release view --web v.version"
    variables = {"version" = "Version"}

[github]
owner = "triaxtec"
repo = "dobby"
