[[workflows]]
name = "Start New Task"

    [[workflows.steps]]
    type = "SelectGitHubIssue"

    [[workflows.steps]]
    type = "SwitchBranches"

[[workflows]]
name = "Finish Development"

    [[workflows.steps]]
    type = "RebaseBranch"
    to = "main"

    [[workflows.steps]]
    type = "BumpVersion"
    rule = "Pre"
    value = "rc"

    [[workflows.steps]]
    type = "Command"
    command = "git add Cargo.toml"

    [[workflows.steps]]
    type = "Command"
    command = "git commit -m \"bump to version\""
    variables = {"version" = "Version"}

    [[workflows.steps]]
    type = "Command"
    command = "git push && git fetch -p -P"

    [[workflows.steps]]
    type = "Command"
    command = "git tag v.version"
    variables = {"version" = "Version"}

    [[workflows.steps]]
    type = "Command"
    command = "git push --tags"

[github]
owner = "triaxtec"
repo = "dobby"
