[packages.knope]
versioned_files = ["crates/knope/Cargo.toml"]
changelog = "CHANGELOG.md"
extra_changelog_sections = [{ name = "Documentation", types = ["docs"] }]

[[packages.knope.assets]]
path = "artifacts/knope-x86_64-unknown-linux-musl.tgz"

[[packages.knope.assets]]
path = "artifacts/knope-x86_64-pc-windows-msvc.tgz"

[[packages.knope.assets]]
path = "artifacts/knope-x86_64-apple-darwin.tgz"

[[packages.knope.assets]]
path = "artifacts/knope-aarch64-apple-darwin.tgz"

[packages.versioning]
versioned_files = ["crates/knope-versioning/Cargo.toml"]
changelog = "crates/knope-versioning/CHANGELOG.md"

[[workflows]]
name = "prepare-release"

[[workflows.steps]]
type = "Command"
command = "git switch -c release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows.steps]]
type = "Command"
shell = true
command = "npx prettier CHANGELOG.md --write && git add CHANGELOG.md"

[[workflows.steps]]
type = "Command"
command = "git commit -m \"chore: prepare release\""

[[workflows.steps]]
type = "Command"
command = "git push --force --set-upstream origin release"

[[workflows.steps]]
type = "CreatePullRequest"
base = "main"

[workflows.steps.title]
template = "chore: prepare releases"

[workflows.steps.body]
template = "This PR was created by Knope. Merging it will create a new release"

[[workflows]]
name = "release"

[[workflows.steps]]
type = "Release"

[[workflows]]
name = "document-change"

[[workflows.steps]]
type = "CreateChangeFile"

[github]
owner = "knope-dev"
repo = "knope"
