[[packages]]
versioned_files = ["Cargo.toml"]
changelog = "CHANGELOG.md"
version_prefix = "v."

[[workflows]]
name = "Start New Task"

[[workflows.steps]]
type = "SelectGitHubIssue"

[[workflows.steps]]
type = "SwitchBranches"

[[workflows]]
name = "Finish Development"

[[workflows.steps]]
type = "Command"
command = "gh pr create --web -p WIP"

[[workflows]]
name = "release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflow.steps]]
type = "Command"
command = "cargo update -w"

[[workflows.steps]]
type = "Command"
command = "npx -y prettier **/*.md --write"

[[workflows.steps]]
type = "Command"
command = "git add Cargo.toml Cargo.lock CHANGELOG.md"

[[workflows.steps]]
type = "Command"
command = "git commit -m \"chore: Bump to version\""
variables = { "version" = "Version" }

[[workflows.steps]]
type = "Command"
command = "git push"

[[workflows.steps]]
type = "Release"

[[workflows]]
name = "prerelease"

[[workflows.steps]]
type = "PrepareRelease"
prerelease_label = "rc"

[[workflow.steps]]
type = "Command"
command = "cargo update -w"

[[workflows.steps]]
type = "Command"
command = "npx -y prettier **/*.md --write"

[[workflows.steps]]
type = "Command"
command = "git add Cargo.toml Cargo.lock CHANGELOG.md"

[[workflows.steps]]
type = "Command"
command = "git commit -m \"chore: Bump to version\""
variables = { "version" = "Version" }

[[workflows.steps]]
type = "Command"
command = "git push"

[[workflows.steps]]
type = "Release"

[github]
owner = "knope-dev"
repo = "knope"
