[env]
RUST_BACKTRACE = 0
CARGO_MAKE_CARGO_VERBOSE_FLAGS = ""
CARGO_MAKE_RUN_CHECK_FORMAT = true
CARGO_MAKE_RUN_CLIPPY = true

[tasks.mdbook]
install_crate = { crate_name = "mdbook", binary = "mdbook", test_arg = "help" }

[tasks.book]
dependencies = ["mdbook"]
command = "mdbook"
args = ["build", "docs"]

[tasks.serve-book]
dependencies = ["mdbook"]
command = "mdbook"
args = ["serve", "docs", "--open"]

[tasks.prettier]
command = "npx"
args = ["prettier", "**/*.md", "--write"]

[tasks.deny]
command = "cargo"
args = ["deny", "--all-features", "check"]

[tasks.dev-test-flow]
dependencies = [
  "deny",
  "format-flow",
  "format-toml-flow",
  "clippy-flow",
  "pre-build",
  "build",
  "post-build",
  "test-flow",
]

[tasks.pre-ci-flow]
dependencies = ["deny", "clippy-flow", "check-format"]
