[env]
RUST_BACKTRACE = 0
CARGO_MAKE_CARGO_VERBOSE_FLAGS = ""

[tasks.mdbook.install_crate]
crate_name = "mdbook"
binary = "mdbook"
test_arg = ["serve", "--help"]
install_command = "cargo-binstall"

[tasks.mdbook-admonish.install_crate]
crate_name = "mdbook-admonish"
binary = "mdbook-admonish"
test_arg = "help"
install_command = "cargo-binstall"

[tasks.mdbook-linkcheck.install_crate]
crate_name = "mdbook-linkcheck"
binary = "mdbook-linkcheck"
test_arg = "--help"
install_command = "cargo-binstall"

[tasks.book-dependencies]
dependencies = ["mdbook-admonish", "mdbook-linkcheck"]

[tasks.book]
dependencies = ["mdbook-minimal", "book-dependencies"]
command = "mdbook"
args = ["build", "docs"]

[tasks.serve-book]
dependencies = ["mdbook", "book-dependencies"]
command = "mdbook"
args = ["serve", "docs", "--open"]

[tasks.prettier]
command = "npx"
args = ["prettier", "**/*.md", "--write", "--prose-wrap=never"]

[tasks.prettier-check]
command = "npx"
args = ["prettier", "**/*.md", "--list-different", "--prose-wrap=never"]

[tasks.deny]
command = "cargo"
args = ["deny", "--all-features", "check"]

[tasks.dev-test-flow]
dependencies = [
  "deny",
  "format-flow",
  "format-toml-flow",
  "prettier",
  "clippy-flow",
  "pre-build",
  "build",
  "post-build",
  "test-flow",
]

[tasks.pre-ci-flow]
dependencies = ["deny", "clippy-flow", "check-format"]
