[env]
RUST_BACKTRACE = 0
CARGO_MAKE_CARGO_VERBOSE_FLAGS = ""

[tasks.mdbook.install_crate]
crate_name = "mdbook"
binary = "mdbook"
test_arg = "--help"

[tasks.mdbook-admonish.install_crate]
crate_name = "mdbook-admonish"
binary = "mdbook-admonish"
test_arg = "help"

[tasks.mdbook-linkcheck.install_crate]
crate_name = "mdbook-linkcheck"
binary = "mdbook-linkcheck"
test_arg = "--help"

[tasks.book-dependencies]
dependencies = ["mdbook", "mdbook-admonish", "mdbook-linkcheck"]

[tasks.book]
dependencies = ["book-dependencies"]
command = "mdbook"
args = ["build", "docs"]

[tasks.serve-book]
dependencies = ["book-dependencies"]
command = "mdbook"
args = ["serve", "docs", "--open"]

[tasks.prettier]
command = "npx"
args = ["prettier", "**/*.md", "--write", "--prose-wrap=never"]

[tasks.prettier-check]
command = "npx"
args = ["prettier", "**/*.md", "--list-different", "--prose-wrap=never"]

[tasks.deny]
command = "cargo"
args = ["deny", "--all-features", "check"]

[tasks.check-format-toml]
install_crate = "taplo-cli"
command = "taplo"
args = ["format", "--check"]

[tasks.check-format]
toolchain = "nightly"
dependencies = ["prettier-check", "check-format-toml"]

[tasks.format]
toolchain = "nightly"

[tasks.dev-test-flow]
dependencies = [
  "deny",
  "format-flow",
  "format-toml-flow",
  "prettier",
  "clippy-flow",
  "pre-build",
  "build",
  "post-build",
  "test-flow",
]

[tasks.pre-ci-flow]
dependencies = ["deny", "clippy-flow"]
