[package]
name = "knope"
description = "A command line tool for automating common development tasks"
version = "0.16.2"
authors = ["Dylan Anthony <contact@dylananthony.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/knope-dev/knope"
homepage = "https://knope.tech"
documentation = "https://knope.tech"
keywords = ["semantic-version", "changelog", "changeset", "git", "github"]
categories = ["command-line-utilities", "development-tools"]
rust-version = "1.71.1"
readme = "../../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.7"
changesets = "0.2.3"
clap = { version = "4.5.4", features = ["cargo", "string", "env"] }
datta = "0.1.1"
env_logger = "0.11.3"
execute = "0.2.13"
git2 = { version = "0.18.3", default-features = false }
git-conventional = "0.12.6"
gix = { version = "0.62.0", default-features = false, features = [
  "max-performance-safe",
] }
indexmap = { version = "2.2.6", features = ["serde"] }
inquire = { version = "0.7.4", default-features = false, features = [
  "crossterm",
] }
itertools = "0.12.1"
knope-versioning = { path = "../knope-versioning", version = "0.0.1", features = [
  "miette",
] }
log = "0.4.21"
miette = { version = "7.2.0", features = ["fancy"] }
platform-dirs = "0.3.0"
relative-path = { version = "1.9.2", features = ["serde"] }
serde = { version = "1.0.198", features = ["derive"] }
serde_json = { version = "1.0.116", features = ["preserve_order"] }
serde_yaml = "0.9.34"
thiserror = "1.0.58"
time = { version = "0.3.36" }
toml = "0.8.12"
ureq = { version = "2.9.6", features = ["json"] }

[dev-dependencies]
pretty_assertions = "1.4.0"
snapbox = { version = "0.5.9", features = ["path"] }
tempfile = "3.10.1"

[lints]
workspace = true
