name: Security audit

on:
  schedule:
    - cron: '0 0 * * 1'
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install cargo-binstall
        run: |
          wget https://github.com/ryankurte/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz
          tar -xvf cargo-binstall-x86_64-unknown-linux-musl.tgz
          cp cargo-binstall $HOME/.cargo/bin

      - name: Install cargo-make
        run: cargo-binstall --no-confirm cargo-make --force

      - name: Install cargo-deny
        run: cargo-binstall --no-confirm cargo-deny --force

      - run: cargo make deny