name: Publish crates

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  publish-crates:
    if:  github.head_ref == 'knope/release' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: Swatinem/rust-cache@v2
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_TOKEN }}
