name: Release Dry Run

on: push

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - uses: Swatinem/rust-cache@v2
      - run: |
          cargo run -- prepare-release --dry-run