name: Release Dry Run

on: push

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - uses: Swatinem/rust-cache@v2
      - run: |
          cargo run -- prepare-release --dry-run