name: Run Checks
on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  checks:
    name: Run Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1
      - name: Install cargo-binstall
        run: |
          wget https://github.com/ryankurte/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz
          tar -xvf cargo-binstall-x86_64-unknown-linux-musl.tgz
          cp cargo-binstall $HOME/.cargo/bin

      - name: Install cargo-make
        run: cargo-binstall --no-confirm cargo-make --force

      - name: Preinstall cargo-deny
        run: cargo-binstall --no-confirm cargo-deny --force

      - name: Run CI
        run: makers ci-flow
        env:
          CARGO_MAKE_BUILD_EXAMPLES: true

      - name: Preinstall mdbook dependencies
        run: cargo-binstall --no-confirm mdbook --force

      - name: Test building the book
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: book

  validate-config:
    name: Validate Knope Config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1
      - name: Run --validate
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -- --validate
