name: Run Checks
on:
  push:
    branches:
      - main
  pull_request: {}
  merge_group:

jobs:
  checks:
    name: Run Checks
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@4.1.1

      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: docs/package-lock.json
      - name: Install cargo-binstall
        run: |
          wget https://github.com/ryankurte/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz
          tar -xvf cargo-binstall-x86_64-unknown-linux-musl.tgz
          cp cargo-binstall $HOME/.cargo/bin

      - name: Install nightly toolchain (for formatting)
        run: rustup toolchain install nightly --component rustfmt

      - name: Install Just
        run: cargo-binstall --no-confirm just --force

      - name: Run CI
        run: just binstall_args="--force" install-all-dependencies ci
  vale:
    name: Vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@reviewdog