name: Run Checks
on:
  push:
    branches:
      - main
  pull_request: {}
  merge_group:

jobs:
  checks:
    name: Run Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: Swatinem/rust-cache@v2
      - name: Install cargo-binstall
        run: |
          wget https://github.com/ryankurte/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz
          tar -xvf cargo-binstall-x86_64-unknown-linux-musl.tgz
          cp cargo-binstall $HOME/.cargo/bin

      - name: Install nightly toolchain (for formatting)
        run: rustup toolchain install nightly --component rustfmt

      - name: Install Just
        run: cargo-binstall --no-confirm just --force

      - name: Run CI
        run: just binstall_args="--force" install-all-dependencies ci
